name: build and deploy code
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀


on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  push_job:
    if: github.event_name == 'push'


    environment: dev
    env:
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      TOKEN_EXPIRATION_TIME: ${{secrets.TOKEN_EXPIRATION_TIME}}
      TOKEN_ALGORITHM: ${{secrets.TOKEN_ALGORITHM}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}

    runs-on: ubuntu-latest
    # run the postgres service to support py app
    services:   
      postgres:   
        image: postgres      
        env:
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    # steps to pull and run py app
    steps:
      - name: first step
        run: echo "this job is because push"
      - name: pulling branch
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - run: pip install -r requirements.txt
      - run: python src/main.py

  pull_request_job:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "this job is because pull request"
      - name: pulling branch
        uses: actions/checkout@v2


