name: build and deploy code
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀


on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  push_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "this job is because push"
      - name: pulling branch
        uses: actions/checkout@v2

  pull_request_job:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "this job is because pull request"
      - name: pulling branch
        uses: actions/checkout@v2


